#!/usr/bin/env bash

# PhpStorm URL Handler
# phpstorm://open?url=file://@file&line=@line
# phpstorm://open?file=@file&line=@line
#
# @license GPL
# @author Stefan Auditor <stefan.auditor@erdfisch.de>

arg=${1}
pattern=".*host_dir=(.*)&docker_dir=(.*)&file(:\/\/|\=)(.*)&line=(.*)$"

# Get the file path.
rawFile=$(echo "${arg}" | sed -r "s/${pattern}/\4/")
localPath=$(echo "${arg}" | sed -r "s/${pattern}/\1/")
dockerPath=$(echo "${arg}" | sed -r "s/${pattern}/\2/")

# Get the line number.
line=$(echo "${arg}" | sed -r "s/${pattern}/\5/")
#Change docker path to local path
file=$(echo "${rawFile}" | sed "s:${dockerPath}:${localPath}:")

# Check if phpstorm|pstorm command exist.
if type phpstorm > /dev/null; then
    /usr/bin/env phpstorm --line "${line}" "${file}"
elif type pstorm > /dev/null; then
    /usr/bin/env pstorm --line "${line}" "${file}"
fi
